New public-external-exposure package.
Configure grafana to listen only on localhost, then serve it through nginx.

diff --git a/pirogue-external-exposure/bin/issue-certificate b/pirogue-external-exposure/bin/issue-certificate
--- a/pirogue-external-exposure/bin/issue-certificate
+++ b/pirogue-external-exposure/bin/issue-certificate
@@ -2,26 +2,46 @@
 
 usage()
 {
-  echo "usage: $0 FQDN MAIL_ADDRESS"
-  echo "       FQDN        : full qualified domain name of the issued certificate"
-  echo "                e.g: my-machine.my-domain.net"
-  echo "       MAIL_ADDRESS: a valid email address to issue a new certificate"
-  echo "                e.g: john.doe@mail.net"
+  echo "usage: $0 DOMAIN EMAIL"
+  echo "       PUBLIC_ACCESS: True | False : enable public access"
+  echo "                      e.g: True"
+  echo "              DOMAIN: full qualified domain name of the issued certificate"
+  echo "                      e.g: my-machine.my-domain.net"
+  echo "               EMAIL: a valid email address to issue a new certificate"
+  echo "                      e.g: john.doe@mail.net"
   exit 1
 }
 
-if test $# -ne 2
+if test $# -ne 3
 then
   usage
 fi
 
-FQDN="${1}"
-MAIL_ADDRESS="${2}"
+PUBLIC_ACCESS="${1}"
+DOMAIN="${2}"
+EMAIL="${3}"
+SELF_SIGNED_CERT_DEST=/var/lib/pirogue/admin/pirogue-external-exposure
 
-/usr/bin/certbot certonly \
-  --pre-hook "service nginx stop" \
-  --post-hook "service nginx start" \
-  --standalone \
-  -d $FQDN \
-  -m $MAIL_ADDRESS \
-  --agree-tos -n
+if test "${PUBLIC_ACCESS}" = 'True'
+then
+  /usr/bin/certbot certonly \
+    --pre-hook "systemctl stop nginx" \
+    --post-hook "systemctl start nginx" \
+    --standalone \
+    -d $DOMAIN \
+    -m $EMAIL \
+    --agree-tos -n
+elif test "${PUBLIC_ACCESS}" = 'False'
+then
+  # CN does not matter very mush since it is fixed
+  # and known by pirogue-admin-client impl
+  mkdir -p "${SELF_SIGNED_CERT_DEST}" && \
+  openssl req -x509 -newkey rsa:4096 \
+    -nodes -days 365 \
+    -keyout "${SELF_SIGNED_CERT_DEST}/privkey.pem" \
+    -out "${SELF_SIGNED_CERT_DEST}/fullchain.pem" \
+    -subj "/CN=pirogue.local" 2> /dev/null
+else
+  >&2 echo "invalid parameter '${PUBLIC_ACCESS}'"
+  usage
+fi
